3esiEmployeeSystemV1/Models/Employee/Training.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace _3esiEmployeeSystemV1.Models.Employee
{
    public class Training
    {
        public int TrainingID { get; set; }

        public int EmployeeID { get; set; }

        [Display(Name = "Course Name")]
        [StringLength(32, ErrorMessage = "The {0} must be less than {1} characters long")]
        public string CourseName { get; set; }

        public int TrainingTypeID { get; set; }

        public int TrainingCategoryID { get; set; }

        [Display(Name = "Offered By")]
        [StringLength(32, ErrorMessage = "The {0} must be less than {1} characters long")]
        public string OfferedBy { get; set; }

        [Display(Name = "Start Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime StartDate { get; set; }

        [Display(Name = "End Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime? EndDate { get; set; }

        [DataType(DataType.Currency)]
        public decimal Amount { get; set; }

        public string Feedback { get; set; }


        //------------------------------ Relationships ------------------------------//

        public virtual Employee Employee { get; set; }

        public virtual TrainingType TrainingType { get; set; }

        public virtual TrainingCategory TrainingCategory { get; set; }
    }

    public class TrainingCategory
    {
        public int ID { get; set; }

        [Display(Name = "Category")]
        [StringLength(32, ErrorMessage = "The {0} must be less than {1} characters long")]
        public string Name { get; set; }

        [StringLength(10, ErrorMessage = "The {0} must be less than {1} characters long")]
        public string Abbreviation { get; set; }

        public virtual List<Training> Trainings { get; set; }
    }

    public class TrainingType
    {
        public int ID { get; set; }

        [Display(Name = "Type")]
        [StringLength(32, ErrorMessage = "The {0} must be less than {1} characters long")]
        public string Name { get; set; }

        [StringLength(10, ErrorMessage = "The {0} must be less than {1} characters long")]
        public string Abbreviation { get; set; }

        public virtual List<Training> Trainings { get; set; }
    }
}

3esiEmployeeSystemV1/ViewModels/TrainingViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace _3esiEmployeeSystemV1.ViewModels
{
    public class TrainingViewModel
    {

        public string LastName { get; set; }

        public string FirstName { get; set; }

        public string CourseName { get; set; }

        public string TrainingType { get; set; }

        public string TrainingCategory { get; set; }

        public string OfferedBy { get; set; }

        public DateTime StartDate { get; set; }

        public DateTime? EndDate { get; set; }

        public decimal Amount { get; set; }

        public string Feedback { get; set; }
    }
}

3esiEmployeeSystemV1/Controllers/ExcelController.cs
using _3esiEmployeeSystemV1.Models;
using _3esiEmployeeSystemV1.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;
using ClosedXML.Excel;
using _3esiEmployeeSystemV1.Helpers;

namespace _3esiEmployeeSystemV1.Controllers
{
    [Authorize(Roles = "Admin, Manager")]
    public class ExcelController : Controller
    {

        public ActionResult ExportCareersToExcel()
        {
            var gv = new GridView();
            gv.DataSource = ReportingHelpers.GetCareerList();
            gv.DataBind();
            Response.ClearContent();
            Response.Buffer = true;
            Response.AddHeader("content-disposition", "attachment; filename=CareersReportExcel.xls");
            Response.ContentType = "application/vnd.ms-excel";
            Response.Charset = "";
            StringWriter objStringWriter = new StringWriter();
            HtmlTextWriter objHtmlTextWriter = new HtmlTextWriter(objStringWriter);
            gv.RenderControl(objHtmlTextWriter);
            Response.Output.Write(objStringWriter.ToString());
            Response.Flush();
            Response.End();
            return View("Index");
        }

        public ActionResult ExportStatusToExcel()
        {
            var gv = new GridView();
            gv.DataSource = ReportingHelpers.GetStatusList();
            gv.DataBind();
            Response.ClearContent();
            Response.Buffer = true;
            Response.AddHeader("content-disposition", "attachment; filename=StatusReportExcel.xls");
            Response.ContentType = "application/vnd.ms-excel";
            Response.Charset = "";
            StringWriter objStringWriter = new StringWriter();
            HtmlTextWriter objHtmlTextWriter = new HtmlTextWriter(objStringWriter);
            gv.RenderControl(objHtmlTextWriter);
            Response.Output.Write(objStringWriter.ToString());
            Response.Flush();
            Response.End();
            return View("Index");
        }

        public ActionResult ExportCompensationsToExcel()
        {
            var gv = new GridView();
            gv.DataSource = ReportingHelpers.GetCompensationList();
            gv.DataBind();
            Response.ClearContent();
            Response.Buffer = true;
            Response.AddHeader("content-disposition", "attachment; filename=CompensationsReportExcel.xls");
            Response.ContentType = "application/vnd.ms-excel";
            Response.Charset = "";
            StringWriter objStringWriter = new StringWriter();
            HtmlTextWriter objHtmlTextWriter = new HtmlTextWriter(objStringWriter);
            gv.RenderControl(objHtmlTextWriter);
            Response.Output.Write(objStringWriter.ToString());
            Response.Flush();
            Response.End();
            return View("Index");
        }

        public ActionResult ExportBenefitsToExcel()
        {
            var gv = new GridView();
            gv.DataSource = ReportingHelpers.GetBenefitList();
            gv.DataBind();
            Response.ClearContent();
            Response.Buffer = true;
            Response.AddHeader("content-disposition", "attachment; filename=BenefitsReportExcel.xls");
            Response.ContentType = "application/vnd.ms-excel";
            Response.Charset = "";
            StringWriter objStringWriter = new StringWriter();
            HtmlTextWriter objHtmlTextWriter = new HtmlTextWriter(objStringWriter);
            gv.RenderControl(objHtmlTextWriter);
            Response.Output.Write(objStringWriter.ToString());
            Response.Flush();
            Response.End();
            return View("Index");
        }

        public ActionResult ExportTrainingsToExcel()
        {
            var gv = new GridView();
            gv.DataSource = ReportingHelpers.GetTrainingList();
            gv.DataBind();
            Response.ClearContent();
            Response.Buffer = true;
            Response.AddHeader("content-disposition", "attachment; filename=TrainingsReportExcel.xls");
            Response.ContentType = "application/vnd.ms-excel";
            Response.Charset = "";
            StringWriter objStringWriter = new StringWriter();
            HtmlTextWriter objHtmlTextWriter = new HtmlTextWriter(objStringWriter);
            gv.RenderControl(objHtmlTextWriter);
            Response.Output.Write(objStringWriter.ToString());
            Response.Flush();
            Response.End();
            return View("Index");
        }

        public ActionResult ExportEmployeesToExcel()
        {
            var gv = new GridView();
            gv.DataSource = ReportingHelpers.GetEmployeeList();
            gv.DataBind();
            Response.ClearContent();
            Response.Buffer = true;
            Response.AddHeader("content-disposition", "attachment; filename=EmployeesReportExcel.xls");
            Response.ContentType = "application/vnd.ms-excel";
            Response.Charset = "";
            StringWriter objStringWriter = new StringWriter();
            HtmlTextWriter objHtmlTextWriter = new HtmlTextWriter(objStringWriter);
            gv.RenderControl(objHtmlTextWriter);
            Response.Output.Write(objStringWriter.ToString());
            Response.Flush();
            Response.End();
            return View("Index");
        }

        // GET: Excel
        public ActionResult Index()
        {
            return View();
        }
    }
}

3esiEmployeeSystemV1/Controllers/TrainingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using _3esiEmployeeSystemV1.Helpers;
using _3esiEmployeeSystemV1.Models;
using _3esiEmployeeSystemV1.Models.Employee;
using PagedList;

namespace _3esiEmployeeSystemV1.Controllers
{
    [Authorize(Roles = "Admin, Manager")]
    public class TrainingsController : Controller
    {
        private EmployeeDBContext db = new EmployeeDBContext();

        // GET: Trainings
        public ActionResult Index(int? id, string searchString, string sortOrder, string currentFilter, int? page, int? pageSize)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            ViewBag.FNameSortParm = sortOrder == "FName" ? "FName_desc" : "FName";
            ViewBag.CatSortParm = sortOrder == "Cat" ? "Cat_desc" : "Cat";
            ViewBag.TypeSortParm = sortOrder == "Type" ? "Type_desc" : "Type";
            ViewBag.AmountSortParm = sortOrder == "Amount" ? "Amount_desc" : "Amount";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var trainings = db.Trainings.Include(t => t.Employee).Include(t => t.TrainingCategory).Include(t => t.TrainingType);

            if (!String.IsNullOrEmpty(searchString))
            {
                trainings = trainings.Where(s => s.Employee.LastName.ToUpper().Contains(searchString.ToUpper())
                                                            || s.Employee.FirstName.ToUpper().Contains(searchString.ToUpper()));
            }

            switch (sortOrder)
            {
                case "name_desc":
                    trainings = trainings.OrderByDescending(s => s.Employee.LastName);
                    break;
                case "FName_desc":
                    trainings = trainings.OrderByDescending(s => s.Employee.FirstName);
                    break;
                case "FName":
                    trainings = trainings.OrderBy(s => s.Employee.FirstName);
                    break;
                case "Date":
                    trainings = trainings.OrderBy(s => s.StartDate);
                    break;
                case "date_desc":
                    trainings = trainings.OrderByDescending(s => s.StartDate);
                    break;
                case "Cat":
                    trainings = trainings.OrderBy(s => s.TrainingCategory.Name);
                    break;
                case "Cat_desc":
                    trainings = trainings.OrderByDescending(s => s.TrainingCategory.Name);
                    break;
                case "Type":
                    trainings = trainings.OrderBy(s => s.TrainingType.Name);
                    break;
                case "Type_desc":
                    trainings = trainings.OrderByDescending(s => s.TrainingType.Name);
                    break;
                case "Amount":
                    trainings = trainings.OrderBy(s => s.Amount);
                    break;
                case "Amount_desc":
                    trainings = trainings.OrderByDescending(s => s.Amount);
                    break;
                default:
                    trainings = trainings.OrderBy(s => s.Employee.LastName);
                    break;
            }

            GlobalVars._pageSize_ = pageSize ?? GlobalVars._pageSize_;
            int pageNumber = (page ?? 1);

            return View(trainings.ToPagedList(pageNumber, GlobalVars._pageSize_));
        }

        // GET: Trainings/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Training training = db.Trainings.Find(id);
            if (training == null)
            {
                return HttpNotFound();
            }
            return View(training);
        }

        // GET: Trainings/Create
        public ActionResult Create()
        {
            ViewBag.EmployeeID = new SelectList(db.Employees.OrderBy(i => i.LastName), "EmployeeID", "FullName");
            ViewBag.TrainingCategoryID = new SelectList(db.TrainingCategories, "ID", "Name");
            ViewBag.TrainingTypeID = new SelectList(db.TrainingTypes, "ID", "Name");
            return View();
        }

        // POST: Trainings/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TrainingID,EmployeeID,CourseName,TrainingTypeID,TrainingCategoryID,OfferedBy,StartDate,EndDate,Amount,Feedback")] Training training)
        {
            if (ModelState.IsValid)
            {
                db.Trainings.Add(training);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.EmployeeID = new SelectList(db.Employees, "EmployeeID", "FullName", training.EmployeeID);
            ViewBag.TrainingCategoryID = new SelectList(db.TrainingCategories, "ID", "Name", training.TrainingCategoryID);
            ViewBag.TrainingTypeID = new SelectList(db.TrainingTypes, "ID", "Name", training.TrainingTypeID);
            return View(training);
        }

        // GET: Trainings/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Training training = db.Trainings.Find(id);
            if (training == null)
            {
                return HttpNotFound();
            }
            ViewBag.EmployeeID = new SelectList(db.Employees, "EmployeeID", "FullName", training.EmployeeID);
            ViewBag.TrainingCategoryID = new SelectList(db.TrainingCategories, "ID", "Name", training.TrainingCategoryID);
            ViewBag.TrainingTypeID = new SelectList(db.TrainingTypes, "ID", "Name", training.TrainingTypeID);
            return View(training);
        }

        // POST: Trainings/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TrainingID,EmployeeID,CourseName,TrainingTypeID,TrainingCategoryID,OfferedBy,StartDate,EndDate,Amount,Feedback")] Training training)
        {
            if (ModelState.IsValid)
            {
                db.Entry(training).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.EmployeeID = new SelectList(db.Employees, "EmployeeID", "FullName", training.EmployeeID);
            ViewBag.TrainingCategoryID = new SelectList(db.TrainingCategories, "ID", "Name", training.TrainingCategoryID);
            ViewBag.TrainingTypeID = new SelectList(db.TrainingTypes, "ID", "Name", training.TrainingTypeID);
            return View(training);
        }

        // GET: Trainings/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Training training = db.Trainings.Find(id);
            if (training == null)
            {
                return HttpNotFound();
            }
            return View(training);
        }

        // POST: Trainings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Training training = db.Trainings.Find(id);
            db.Trainings.Remove(training);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

3esiEmployeeSystemV1/Views/Trainings/Create.cshtml
@model _3esiEmployeeSystemV1.Models.Employee.Training

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Training</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeID, "EmployeeID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EmployeeID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EmployeeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CourseName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CourseName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CourseName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TrainingTypeID, "TrainingTypeID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TrainingTypeID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TrainingTypeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TrainingCategoryID, "TrainingCategoryID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TrainingCategoryID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TrainingCategoryID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OfferedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OfferedBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OfferedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Feedback, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Feedback, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Feedback, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

3esiEmployeeSystemV1/Views/Trainings/Delete.cshtml
@model _3esiEmployeeSystemV1.Models.Employee.Training

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Training</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Employee.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Employee.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TrainingCategory.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TrainingCategory.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TrainingType.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TrainingType.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CourseName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CourseName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OfferedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OfferedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Amount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Feedback)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Feedback)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

3esiEmployeeSystemV1/Views/Trainings/Details.cshtml
@model _3esiEmployeeSystemV1.Models.Employee.Training

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Training</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Employee.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Employee.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TrainingCategory.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TrainingCategory.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TrainingType.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TrainingType.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CourseName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CourseName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OfferedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OfferedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Amount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Feedback)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Feedback)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.TrainingID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

3esiEmployeeSystemV1/Views/Trainings/Index.cshtml
@model PagedList.IPagedList<_3esiEmployeeSystemV1.Models.Employee.Training>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Index";
}

<h2>Trainings</h2>

@using (Html.BeginForm("Index", "Compensations", FormMethod.Get))
{
    <p>
        Find by name: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" />
    </p>
}

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Last Name", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("First Name", "Index", new { sortOrder = ViewBag.FNameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Training Category", "Index", new { sortOrder = ViewBag.CatSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Training Type", "Index", new { sortOrder = ViewBag.TypeSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            Course Name
        </th>
        <th>
            Offered By
        </th>
        <th>
            @Html.ActionLink("Start Date", "Index", new { sortOrder = ViewBag.DateSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            End Date
        </th>
        <th>
            @Html.ActionLink("Amount", "Index", new { sortOrder = ViewBag.AmountSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Employee.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Employee.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TrainingCategory.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TrainingType.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CourseName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OfferedBy)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StartDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EndDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Amount)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.TrainingID }) |
            @Html.ActionLink("Details", "Details", new { id=item.TrainingID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.TrainingID })
        </td>
    </tr>
}

</table>

<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter, pageSize = ViewBag.PageSize }))

@using (Html.BeginForm("Index", "Trainings", FormMethod.Post))
{
    <p>
        Items per Page @Html.DropDownList("PageSize", new SelectList(new Dictionary<string, int> { { "5", 5 }, { "10", 10 }, { "20", 20 }, { "100", 100 }, { "All", Model.TotalItemCount } }, "Value", "Key", Model.Count))
        <input type="submit" value="&raquo;" class="button" />
    </p>
}

<br />
@using (Html.BeginForm("ExportTrainingsToExcel", "Excel", FormMethod.Post))
{
    <input type="submit" value="Export to Excel" class="button" />
}