3esiEmployeeSystemV1/Models/Employee/Benefit.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace _3esiEmployeeSystemV1.Models.Employee
{
    public class Benefit
    {
        public int BenefitID { get; set; }

        public int EmployeeID { get; set; }

        [Required]
        [Display(Name = "Effective Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime EffectiveDate { get; set; }

        [Display(Name = "End Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime? EndDate { get; set; }

        [Display(Name = "Benefit Plan")]
        [StringLength(32, ErrorMessage = "The {0} must be less than {1} characters long")]
        public string BenefitPlan { get; set; }

        public int BenefitTypeID { get; set; }

        [DataType(DataType.Currency)]
        public decimal Amount { get; set; }

        public int CurrencyID { get; set; }

        public string Comment { get; set; }

        //------------------------------ Relationships ------------------------------//

        public virtual Employee Employee { get; set; }

        public virtual BenefitType BenefitType { get; set; }

        public virtual Currency Currency { get; set; }



    }
    public class BenefitType
    {

        public int ID { get; set; }

        [Display(Name = "Benefit Type")]
        [StringLength(32, ErrorMessage = "The {0} must be less than {1} characters long")]
        public string Name { get; set; }

        [StringLength(10, ErrorMessage = "The {0} must be less than {1} characters long")]
        public string Abbreviation { get; set; }

        public virtual List<Benefit> Benefits { get; set; }

    };
}

3esiEmployeeSystemV1/ViewModels/BenefitViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace _3esiEmployeeSystemV1.ViewModels
{
    public class BenefitViewModel
    {
        public string LastName { get; set; }

        public string FirstName { get; set; }

        public DateTime EffectiveDate { get; set; }

        public DateTime? EndDate { get; set; }

        public string BenefitPlan { get; set; }

        public string BenefitType { get; set; }

        public decimal Amount { get; set; }

        public string Currency { get; set; }

        public string Comment { get; set; }
    }
}

3esiEmployeeSystemV1/Controllers/BenefitsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using _3esiEmployeeSystemV1.Helpers;
using _3esiEmployeeSystemV1.Models;
using _3esiEmployeeSystemV1.Models.Employee;
using PagedList;

namespace _3esiEmployeeSystemV1.Controllers
{
    [Authorize(Roles = "Admin, Manager")]
    public class BenefitsController : Controller
    {
        private EmployeeDBContext db = new EmployeeDBContext();

        // GET: Benefits
        public ActionResult Index(int? id, string searchString, string sortOrder, string currentFilter, int? page, int? pageSize)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            ViewBag.FNameSortParm = sortOrder == "FName" ? "FName_desc" : "FName";
            ViewBag.TypeSortParm = sortOrder == "Type" ? "Type_desc" : "Type";
            ViewBag.PlanSortParm = sortOrder == "Plan" ? "Plan_desc" : "Plan";
            ViewBag.AmountSortParm = sortOrder == "Amount" ? "Amount_desc" : "Amount";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var benefits = db.Benefits.Include(b => b.BenefitType).Include(b => b.Currency).Include(b => b.Employee);

            if (!String.IsNullOrEmpty(searchString))
            {
                benefits = benefits.Where(s => s.Employee.LastName.ToUpper().Contains(searchString.ToUpper())
                                                            || s.Employee.FirstName.ToUpper().Contains(searchString.ToUpper()));
            }

            switch (sortOrder)
            {
                case "name_desc":
                    benefits = benefits.OrderByDescending(s => s.Employee.LastName);
                    break;
                case "Date":
                    benefits = benefits.OrderBy(s => s.EffectiveDate);
                    break;
                case "date_desc":
                    benefits = benefits.OrderByDescending(s => s.EffectiveDate);
                    break;
                case "FName_desc":
                    benefits = benefits.OrderByDescending(s => s.Employee.FirstName);
                    break;
                case "FName":
                    benefits = benefits.OrderBy(s => s.Employee.FirstName);
                    break;
                case "Type_desc":
                    benefits = benefits.OrderByDescending(s => s.BenefitType.Name);
                    break;
                case "Type":
                    benefits = benefits.OrderBy(s => s.BenefitType.Name);
                    break;
                case "Plan_desc":
                    benefits = benefits.OrderByDescending(s => s.BenefitPlan);
                    break;
                case "Plan":
                    benefits = benefits.OrderBy(s => s.BenefitPlan);
                    break;
                case "Amount_desc":
                    benefits = benefits.OrderByDescending(s => s.Amount);
                    break;
                case "Amount":
                    benefits = benefits.OrderBy(s => s.Amount);
                    break;
                default:
                    benefits = benefits.OrderBy(s => s.Employee.LastName);
                    break;
            }

            GlobalVars._pageSize_ = pageSize ?? GlobalVars._pageSize_;
            int pageNumber = (page ?? 1);


            return View(benefits.ToPagedList(pageNumber, GlobalVars._pageSize_));
        }

        // GET: Benefits/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Benefit benefit = db.Benefits.Find(id);
            if (benefit == null)
            {
                return HttpNotFound();
            }
            return View(benefit);
        }

        // GET: Benefits/Create
        public ActionResult Create()
        {
            ViewBag.BenefitTypeID = new SelectList(db.BenefitTypes, "ID", "Name");
            ViewBag.CurrencyID = new SelectList(db.Currencies, "ID", "Name");
            ViewBag.EmployeeID = new SelectList(db.Employees.OrderBy(i => i.LastName), "EmployeeID", "FullName");
            return View();
        }

        // POST: Benefits/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BenefitID,EmployeeID,EffectiveDate,EndDate,BenefitPlan,BenefitTypeID,Amount,CurrencyID,Comment")] Benefit benefit)
        {
            if (ModelState.IsValid)
            {
                db.Benefits.Add(benefit);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.BenefitTypeID = new SelectList(db.BenefitTypes, "ID", "Name", benefit.BenefitTypeID);
            ViewBag.CurrencyID = new SelectList(db.Currencies, "ID", "Name", benefit.CurrencyID);
            ViewBag.EmployeeID = new SelectList(db.Employees, "EmployeeID", "FullName", benefit.EmployeeID);
            return View(benefit);
        }

        // GET: Benefits/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Benefit benefit = db.Benefits.Find(id);
            if (benefit == null)
            {
                return HttpNotFound();
            }
            ViewBag.BenefitTypeID = new SelectList(db.BenefitTypes, "ID", "Name", benefit.BenefitTypeID);
            ViewBag.CurrencyID = new SelectList(db.Currencies, "ID", "Name", benefit.CurrencyID);
            ViewBag.EmployeeID = new SelectList(db.Employees, "EmployeeID", "FullName", benefit.EmployeeID);
            return View(benefit);
        }

        // POST: Benefits/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BenefitID,EmployeeID,EffectiveDate,EndDate,BenefitPlan,BenefitTypeID,Amount,CurrencyID,Comment")] Benefit benefit)
        {
            if (ModelState.IsValid)
            {
                db.Entry(benefit).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.BenefitTypeID = new SelectList(db.BenefitTypes, "ID", "Name", benefit.BenefitTypeID);
            ViewBag.CurrencyID = new SelectList(db.Currencies, "ID", "Name", benefit.CurrencyID);
            ViewBag.EmployeeID = new SelectList(db.Employees, "EmployeeID", "FullName", benefit.EmployeeID);
            return View(benefit);
        }

        // GET: Benefits/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Benefit benefit = db.Benefits.Find(id);
            if (benefit == null)
            {
                return HttpNotFound();
            }
            return View(benefit);
        }

        // POST: Benefits/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Benefit benefit = db.Benefits.Find(id);
            db.Benefits.Remove(benefit);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

3esiEmployeeSystemV1/Controllers/ExcelController.cs
using _3esiEmployeeSystemV1.Models;
using _3esiEmployeeSystemV1.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;
using ClosedXML.Excel;
using _3esiEmployeeSystemV1.Helpers;

namespace _3esiEmployeeSystemV1.Controllers
{
    [Authorize(Roles = "Admin, Manager")]
    public class ExcelController : Controller
    {

        public ActionResult ExportCareersToExcel()
        {
            var gv = new GridView();
            gv.DataSource = ReportingHelpers.GetCareerList();
            gv.DataBind();
            Response.ClearContent();
            Response.Buffer = true;
            Response.AddHeader("content-disposition", "attachment; filename=CareersReportExcel.xls");
            Response.ContentType = "application/vnd.ms-excel";
            Response.Charset = "";
            StringWriter objStringWriter = new StringWriter();
            HtmlTextWriter objHtmlTextWriter = new HtmlTextWriter(objStringWriter);
            gv.RenderControl(objHtmlTextWriter);
            Response.Output.Write(objStringWriter.ToString());
            Response.Flush();
            Response.End();
            return View("Index");
        }

        public ActionResult ExportStatusToExcel()
        {
            var gv = new GridView();
            gv.DataSource = ReportingHelpers.GetStatusList();
            gv.DataBind();
            Response.ClearContent();
            Response.Buffer = true;
            Response.AddHeader("content-disposition", "attachment; filename=StatusReportExcel.xls");
            Response.ContentType = "application/vnd.ms-excel";
            Response.Charset = "";
            StringWriter objStringWriter = new StringWriter();
            HtmlTextWriter objHtmlTextWriter = new HtmlTextWriter(objStringWriter);
            gv.RenderControl(objHtmlTextWriter);
            Response.Output.Write(objStringWriter.ToString());
            Response.Flush();
            Response.End();
            return View("Index");
        }

        public ActionResult ExportCompensationsToExcel()
        {
            var gv = new GridView();
            gv.DataSource = ReportingHelpers.GetCompensationList();
            gv.DataBind();
            Response.ClearContent();
            Response.Buffer = true;
            Response.AddHeader("content-disposition", "attachment; filename=CompensationsReportExcel.xls");
            Response.ContentType = "application/vnd.ms-excel";
            Response.Charset = "";
            StringWriter objStringWriter = new StringWriter();
            HtmlTextWriter objHtmlTextWriter = new HtmlTextWriter(objStringWriter);
            gv.RenderControl(objHtmlTextWriter);
            Response.Output.Write(objStringWriter.ToString());
            Response.Flush();
            Response.End();
            return View("Index");
        }

        public ActionResult ExportBenefitsToExcel()
        {
            var gv = new GridView();
            gv.DataSource = ReportingHelpers.GetBenefitList();
            gv.DataBind();
            Response.ClearContent();
            Response.Buffer = true;
            Response.AddHeader("content-disposition", "attachment; filename=BenefitsReportExcel.xls");
            Response.ContentType = "application/vnd.ms-excel";
            Response.Charset = "";
            StringWriter objStringWriter = new StringWriter();
            HtmlTextWriter objHtmlTextWriter = new HtmlTextWriter(objStringWriter);
            gv.RenderControl(objHtmlTextWriter);
            Response.Output.Write(objStringWriter.ToString());
            Response.Flush();
            Response.End();
            return View("Index");
        }

        public ActionResult ExportTrainingsToExcel()
        {
            var gv = new GridView();
            gv.DataSource = ReportingHelpers.GetTrainingList();
            gv.DataBind();
            Response.ClearContent();
            Response.Buffer = true;
            Response.AddHeader("content-disposition", "attachment; filename=TrainingsReportExcel.xls");
            Response.ContentType = "application/vnd.ms-excel";
            Response.Charset = "";
            StringWriter objStringWriter = new StringWriter();
            HtmlTextWriter objHtmlTextWriter = new HtmlTextWriter(objStringWriter);
            gv.RenderControl(objHtmlTextWriter);
            Response.Output.Write(objStringWriter.ToString());
            Response.Flush();
            Response.End();
            return View("Index");
        }

        public ActionResult ExportEmployeesToExcel()
        {
            var gv = new GridView();
            gv.DataSource = ReportingHelpers.GetEmployeeList();
            gv.DataBind();
            Response.ClearContent();
            Response.Buffer = true;
            Response.AddHeader("content-disposition", "attachment; filename=EmployeesReportExcel.xls");
            Response.ContentType = "application/vnd.ms-excel";
            Response.Charset = "";
            StringWriter objStringWriter = new StringWriter();
            HtmlTextWriter objHtmlTextWriter = new HtmlTextWriter(objStringWriter);
            gv.RenderControl(objHtmlTextWriter);
            Response.Output.Write(objStringWriter.ToString());
            Response.Flush();
            Response.End();
            return View("Index");
        }

        // GET: Excel
        public ActionResult Index()
        {
            return View();
        }
    }
}

3esiEmployeeSystemV1/Views/Benefits/Create.cshtml
@model _3esiEmployeeSystemV1.Models.Employee.Benefit

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Benefit</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeID, "EmployeeID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EmployeeID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EmployeeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EffectiveDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EffectiveDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EffectiveDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BenefitPlan, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BenefitPlan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BenefitPlan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BenefitTypeID, "BenefitTypeID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("BenefitTypeID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.BenefitTypeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CurrencyID, "CurrencyID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CurrencyID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CurrencyID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Comment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Comment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Comment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

3esiEmployeeSystemV1/Views/Benefits/Delete.cshtml
@model _3esiEmployeeSystemV1.Models.Employee.Benefit

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Benefit</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BenefitType.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BenefitType.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Currency.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Currency.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Employee.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Employee.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EffectiveDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EffectiveDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BenefitPlan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BenefitPlan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Amount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Comment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comment)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

3esiEmployeeSystemV1/Views/Benefits/Details.cshtml
@model _3esiEmployeeSystemV1.Models.Employee.Benefit

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Benefit</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BenefitType.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BenefitType.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Currency.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Currency.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Employee.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Employee.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EffectiveDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EffectiveDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BenefitPlan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BenefitPlan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Amount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Comment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comment)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.BenefitID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

3esiEmployeeSystemV1/Views/Benefits/Index.cshtml
@model PagedList.IPagedList<_3esiEmployeeSystemV1.Models.Employee.Benefit>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Index";
}

<h2>Benefits</h2>

@using (Html.BeginForm("Index", "Compensations", FormMethod.Get))
{
    <p>
        Find by name: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" />
    </p>
}

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Last Name", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("First Name", "Index", new { sortOrder = ViewBag.FNameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Effective Date", "Index", new { sortOrder = ViewBag.DateSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            End Date
        </th>
        <th>
            @Html.ActionLink("Benefit Plan", "Index", new { sortOrder = ViewBag.PlanSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Benefit Type", "Index", new { sortOrder = ViewBag.TypeSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Amount", "Index", new { sortOrder = ViewBag.AmountSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            Currency
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Employee.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Employee.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EffectiveDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EndDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BenefitPlan)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BenefitType.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Amount)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Currency.Name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.BenefitID }) |
            @Html.ActionLink("Details", "Details", new { id=item.BenefitID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.BenefitID })
        </td>
    </tr>
}

</table>

<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter, pageSize = ViewBag.PageSize }))

@using (Html.BeginForm("Index", "Benefits", FormMethod.Post))
{
    <p>
        Items per Page @Html.DropDownList("PageSize", new SelectList(new Dictionary<string, int> { { "5", 5 }, { "10", 10 }, { "20", 20 }, { "100", 100 }, { "All", Model.TotalItemCount } }, "Value", "Key", Model.Count))
        <input type="submit" value="&raquo;" class="button" />
    </p>
}

<br />
@using (Html.BeginForm("ExportBenefitsToExcel", "Excel", FormMethod.Post))
{
    <input type="submit" value="Export to Excel" class="button" />
}