3esiEmployeeSystemV1/Controllers/ExcelController.cs
using _3esiEmployeeSystemV1.Models;
using _3esiEmployeeSystemV1.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;
using ClosedXML.Excel;
using _3esiEmployeeSystemV1.Helpers;

namespace _3esiEmployeeSystemV1.Controllers
{
    [Authorize(Roles = "Admin, Manager")]
    public class ExcelController : Controller
    {

        public ActionResult ExportCareersToExcel()
        {
            var gv = new GridView();
            gv.DataSource = ReportingHelpers.GetCareerList();
            gv.DataBind();
            Response.ClearContent();
            Response.Buffer = true;
            Response.AddHeader("content-disposition", "attachment; filename=CareersReportExcel.xls");
            Response.ContentType = "application/vnd.ms-excel";
            Response.Charset = "";
            StringWriter objStringWriter = new StringWriter();
            HtmlTextWriter objHtmlTextWriter = new HtmlTextWriter(objStringWriter);
            gv.RenderControl(objHtmlTextWriter);
            Response.Output.Write(objStringWriter.ToString());
            Response.Flush();
            Response.End();
            return View("Index");
        }

        public ActionResult ExportStatusToExcel()
        {
            var gv = new GridView();
            gv.DataSource = ReportingHelpers.GetStatusList();
            gv.DataBind();
            Response.ClearContent();
            Response.Buffer = true;
            Response.AddHeader("content-disposition", "attachment; filename=StatusReportExcel.xls");
            Response.ContentType = "application/vnd.ms-excel";
            Response.Charset = "";
            StringWriter objStringWriter = new StringWriter();
            HtmlTextWriter objHtmlTextWriter = new HtmlTextWriter(objStringWriter);
            gv.RenderControl(objHtmlTextWriter);
            Response.Output.Write(objStringWriter.ToString());
            Response.Flush();
            Response.End();
            return View("Index");
        }

        public ActionResult ExportCompensationsToExcel()
        {
            var gv = new GridView();
            gv.DataSource = ReportingHelpers.GetCompensationList();
            gv.DataBind();
            Response.ClearContent();
            Response.Buffer = true;
            Response.AddHeader("content-disposition", "attachment; filename=CompensationsReportExcel.xls");
            Response.ContentType = "application/vnd.ms-excel";
            Response.Charset = "";
            StringWriter objStringWriter = new StringWriter();
            HtmlTextWriter objHtmlTextWriter = new HtmlTextWriter(objStringWriter);
            gv.RenderControl(objHtmlTextWriter);
            Response.Output.Write(objStringWriter.ToString());
            Response.Flush();
            Response.End();
            return View("Index");
        }

        public ActionResult ExportBenefitsToExcel()
        {
            var gv = new GridView();
            gv.DataSource = ReportingHelpers.GetBenefitList();
            gv.DataBind();
            Response.ClearContent();
            Response.Buffer = true;
            Response.AddHeader("content-disposition", "attachment; filename=BenefitsReportExcel.xls");
            Response.ContentType = "application/vnd.ms-excel";
            Response.Charset = "";
            StringWriter objStringWriter = new StringWriter();
            HtmlTextWriter objHtmlTextWriter = new HtmlTextWriter(objStringWriter);
            gv.RenderControl(objHtmlTextWriter);
            Response.Output.Write(objStringWriter.ToString());
            Response.Flush();
            Response.End();
            return View("Index");
        }

        public ActionResult ExportTrainingsToExcel()
        {
            var gv = new GridView();
            gv.DataSource = ReportingHelpers.GetTrainingList();
            gv.DataBind();
            Response.ClearContent();
            Response.Buffer = true;
            Response.AddHeader("content-disposition", "attachment; filename=TrainingsReportExcel.xls");
            Response.ContentType = "application/vnd.ms-excel";
            Response.Charset = "";
            StringWriter objStringWriter = new StringWriter();
            HtmlTextWriter objHtmlTextWriter = new HtmlTextWriter(objStringWriter);
            gv.RenderControl(objHtmlTextWriter);
            Response.Output.Write(objStringWriter.ToString());
            Response.Flush();
            Response.End();
            return View("Index");
        }

        public ActionResult ExportEmployeesToExcel()
        {
            var gv = new GridView();
            gv.DataSource = ReportingHelpers.GetEmployeeList();
            gv.DataBind();
            Response.ClearContent();
            Response.Buffer = true;
            Response.AddHeader("content-disposition", "attachment; filename=EmployeesReportExcel.xls");
            Response.ContentType = "application/vnd.ms-excel";
            Response.Charset = "";
            StringWriter objStringWriter = new StringWriter();
            HtmlTextWriter objHtmlTextWriter = new HtmlTextWriter(objStringWriter);
            gv.RenderControl(objHtmlTextWriter);
            Response.Output.Write(objStringWriter.ToString());
            Response.Flush();
            Response.End();
            return View("Index");
        }

        // GET: Excel
        public ActionResult Index()
        {
            return View();
        }
    }
}

3esiEmployeeSystemV1/Controllers/ParkingAccessesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using _3esiEmployeeSystemV1.Helpers;
using _3esiEmployeeSystemV1.Models;
using _3esiEmployeeSystemV1.Models.Employee;
using PagedList;

namespace _3esiEmployeeSystemV1.Controllers
{
    [Authorize(Roles = "Admin, Manager, Employee")]
    public class ParkingAccessesController : Controller
    {
        private EmployeeDBContext db = new EmployeeDBContext();

        // GET: ParkingAccesses
        public ActionResult Index(int? id, string searchString, string sortOrder, string currentFilter, int? page, int? pageSize)
        {

            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            ViewBag.FNameSortParm = sortOrder == "FName" ? "FName_desc" : "FName";
            ViewBag.ParkSortParm = sortOrder == "Park" ? "Park_desc" : "Park";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var parkingAccesses = db.ParkingAccesses.Include(p => p.Employee).Include(p => p.Parking);

            if (!String.IsNullOrEmpty(searchString))
            {
                parkingAccesses = parkingAccesses.Where(s => s.Employee.LastName.ToUpper().Contains(searchString.ToUpper())
                                                            || s.Employee.FirstName.ToUpper().Contains(searchString.ToUpper()));
            }

            switch (sortOrder)
            {
                case "name_desc":
                    parkingAccesses = parkingAccesses.OrderByDescending(s => s.Employee.LastName);
                    break;
                case "Date":
                    parkingAccesses = parkingAccesses.OrderBy(s => s.EffectiveDate);
                    break;
                case "date_desc":
                    parkingAccesses = parkingAccesses.OrderByDescending(s => s.EffectiveDate);
                    break;
                case "FName_desc":
                    parkingAccesses = parkingAccesses.OrderByDescending(s => s.Employee.FirstName);
                    break;
                case "FName":
                    parkingAccesses = parkingAccesses.OrderBy(s => s.Employee.FirstName);
                    break;
                case "Park_desc":
                    parkingAccesses = parkingAccesses.OrderByDescending(s => s.Parking.Address);
                    break;
                case "Park":
                    parkingAccesses = parkingAccesses.OrderBy(s => s.Parking.Address);
                    break;
                default:
                    parkingAccesses = parkingAccesses.OrderBy(s => s.Employee.LastName);
                    break;
            }

            GlobalVars._pageSize_ = pageSize ?? GlobalVars._pageSize_;
            int pageNumber = (page ?? 1);

            return View(parkingAccesses.ToPagedList(pageNumber, GlobalVars._pageSize_));
        }

        // GET: ParkingAccesses/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ParkingAccess parkingAccess = db.ParkingAccesses.Find(id);
            if (parkingAccess == null)
            {
                return HttpNotFound();
            }
            return View(parkingAccess);
        }

        // GET: ParkingAccesses/Create
        public ActionResult Create()
        {
            ViewBag.EmployeeID = new SelectList(db.Employees.OrderBy(i => i.LastName), "EmployeeID", "FullName");
            ViewBag.ParkingID = new SelectList(db.Parkings, "ParkingID", "Address");
            return View();
        }

        // POST: ParkingAccesses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ParkingAccessID,EmployeeID,ParkingID,EffectiveDate,CarModel,PlateNumber")] ParkingAccess parkingAccess)
        {
            if (ModelState.IsValid)
            {
                db.ParkingAccesses.Add(parkingAccess);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.EmployeeID = new SelectList(db.Employees, "EmployeeID", "FullName", parkingAccess.EmployeeID);
            ViewBag.ParkingID = new SelectList(db.Parkings, "ParkingID", "Address", parkingAccess.ParkingID);
            return View(parkingAccess);
        }

        // GET: ParkingAccesses/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ParkingAccess parkingAccess = db.ParkingAccesses.Find(id);
            if (parkingAccess == null)
            {
                return HttpNotFound();
            }
            ViewBag.EmployeeID = new SelectList(db.Employees, "EmployeeID", "FullName", parkingAccess.EmployeeID);
            ViewBag.ParkingID = new SelectList(db.Parkings, "ParkingID", "Address", parkingAccess.ParkingID);
            return View(parkingAccess);
        }

        // POST: ParkingAccesses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ParkingAccessID,EmployeeID,ParkingID,EffectiveDate,CarModel,PlateNumber")] ParkingAccess parkingAccess)
        {
            if (ModelState.IsValid)
            {
                db.Entry(parkingAccess).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.EmployeeID = new SelectList(db.Employees, "EmployeeID", "FullName", parkingAccess.EmployeeID);
            ViewBag.ParkingID = new SelectList(db.Parkings, "ParkingID", "Address", parkingAccess.ParkingID);
            return View(parkingAccess);
        }

        // GET: ParkingAccesses/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ParkingAccess parkingAccess = db.ParkingAccesses.Find(id);
            if (parkingAccess == null)
            {
                return HttpNotFound();
            }
            return View(parkingAccess);
        }

        // POST: ParkingAccesses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ParkingAccess parkingAccess = db.ParkingAccesses.Find(id);
            db.ParkingAccesses.Remove(parkingAccess);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

3esiEmployeeSystemV1/Views/ParkingAccesses/Create.cshtml
@model _3esiEmployeeSystemV1.Models.Employee.ParkingAccess

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ParkingAccess</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeID, "EmployeeID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EmployeeID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EmployeeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ParkingID, "ParkingID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ParkingID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ParkingID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EffectiveDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EffectiveDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EffectiveDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CarModel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CarModel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CarModel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PlateNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PlateNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PlateNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

3esiEmployeeSystemV1/Views/ParkingAccesses/Delete.cshtml
@model _3esiEmployeeSystemV1.Models.Employee.ParkingAccess

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ParkingAccess</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Employee.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Employee.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Parking.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Parking.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EffectiveDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EffectiveDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CarModel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CarModel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PlateNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PlateNumber)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

3esiEmployeeSystemV1/Views/ParkingAccesses/Details.cshtml
@model _3esiEmployeeSystemV1.Models.Employee.ParkingAccess

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ParkingAccess</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Employee.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Employee.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Parking.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Parking.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EffectiveDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EffectiveDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CarModel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CarModel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PlateNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PlateNumber)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ParkingAccessID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

3esiEmployeeSystemV1/Views/ParkingAccesses/Edit.cshtml
@model _3esiEmployeeSystemV1.Models.Employee.ParkingAccess

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ParkingAccess</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ParkingAccessID)

        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeID, "EmployeeID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EmployeeID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EmployeeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ParkingID, "ParkingID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ParkingID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ParkingID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EffectiveDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EffectiveDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EffectiveDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CarModel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CarModel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CarModel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PlateNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PlateNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PlateNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

3esiEmployeeSystemV1/Views/ParkingAccesses/Index.cshtml
@model PagedList.IPagedList<_3esiEmployeeSystemV1.Models.Employee.ParkingAccess>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Index";
}

<h2>Parking Accesses</h2>

@using (Html.BeginForm("Index", "ParkingAccess", FormMethod.Get))
{
    <p>
        Find by name: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" />
    </p>
}

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Last Name", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("First Name", "Index", new { sortOrder = ViewBag.FNameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Address", "Index", new { sortOrder = ViewBag.ParkSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Effective Date", "Index", new { sortOrder = ViewBag.DateSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            Car Model
        </th>
        <th>
            Plate Number
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Employee.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Employee.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Parking.Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EffectiveDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CarModel)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PlateNumber)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ParkingAccessID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ParkingAccessID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ParkingAccessID })
        </td>
    </tr>
}

</table>

<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter, pageSize = ViewBag.PageSize }))

@using (Html.BeginForm("Index", "ParkingAccesses", FormMethod.Post))
{
    <p>
        Items per Page @Html.DropDownList("PageSize", new SelectList(new Dictionary<string, int> { { "5", 5 }, { "10", 10 }, { "20", 20 }, { "100", 100 }, { "All", Model.TotalItemCount } }, "Value", "Key", Model.Count))
        <input type="submit" value="&raquo;" class="button" />
    </p>
}

<br />
@using (Html.BeginForm("ExportParkingAccessesToExcel", "Excel", FormMethod.Post))
{
    <input type="submit" value="Export to Excel" class="button" />
}